force-app/main/default/objects/Meetup__c/Meetup__c.object-meta.xml
<CustomObject>
    <label>Meetup</label>
    <nameField>
        <label>Meetup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meetup__c/fields/RegistrationCode__c.field-meta.xml
<CustomField>
    <fullName>RegistrationCode__c</fullName>
    <label>RegistrationCode</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MeetupRegistrationController.cls
public with sharing class MeetupRegistrationController {
    
    @AuraEnabled(cacheable=true)
    public static List<Meetup__c> getMeetupsByName(String searchName){
        try {
            return [SELECT Id, Name, RegistrationCode__c FROM Meetup__c WHERE Name LIKE :searchName];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static Meetup__c getMeetupByRegistrationCode(String registrationCode) {
        try {
            return [SELECT Id, Name, RegistrationLimit__c, RegistrationCode__c, Status__c FROM Meetup__c WHERE RegistrationCode__c = :registrationCode AND Status__c = 'Open'];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}