force-app/main/default/objects/Meetup__c/Meetup__c.object-meta.xml
<CustomObject>
    <label>Meetup</label>
    <nameField>
        <label>Meetup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meetup__c/fields/RegistrationCode__c.field-meta.xml
<CustomField>
    <fullName>RegistrationCode__c</fullName>
    <label>RegistrationCode</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Meetup__c/fields/RegistrationCount__c.field-meta.xml
<CustomField>
    <fullName>RegistrationCount__c</fullName>
    <label>RegistrationCount</label>
    <summaryForeignKey>MeetupRegistration__c.Meetup__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/MeetupRegistration__c/MeetupRegistration__c.object-meta.xml
<CustomObject>
    <label>MeetupRegistration</label>
    <nameField>
        <label>Registration Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MeetupRegistrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MeetupRegistration__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>FirstName</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MeetupRegistrationDAC.cls
public with sharing class MeetupRegistrationDAC {
    private List<MeetupRegistration__c> meetupRegs;

    public MeetupRegistrationDAC(List<MeetupRegistration__c> meetupRegs) {
        this.meetupRegs = meetupRegs;
    }

    public MeetupRegistrationDTO getDTO() {
        Set<Id> meetupIds = new Set<Id>();
       
        for(MeetupRegistration__c registration : this.meetupRegs) {
            meetupIds.add(registration.Meetup__c);
        }

        Map<Id, Meetup__c> meetups = new Map<Id, Meetup__c>([SELECT Id, Name, Status__c, RegistrationCode__c, RegistrationLimit__c, RegistrationCount__c, (SELECT Id, FirstName__c, LastName__c, Email__c, Name FROM MeetupRegistrations__r) FROM Meetup__c WHERE Id in :meetupIds]);
        Map<Id, List<MeetupRegistration__c>> meetupsToRegistrations = new Map<Id, List<MeetupRegistration__c>>();
        Map<Id, Meetup__c> registrationToMeetup = new Map<Id, Meetup__c>();

        for(MeetupRegistration__c registration : this.meetupRegs) {
            Meetup__c meetup = meetups.get(registration.Meetup__c);
            if(meetupsToRegistrations.keySet().contains(meetup.Id)){
                meetupsToRegistrations.get(meetup.Id).add(registration);
            } else {
                List<MeetupRegistration__c> regs = new List<MeetupRegistration__c>();
                regs.add(registration);
                meetupsToRegistrations.put(meetup.Id, regs);
            }

            registrationToMeetup.put(registration.Id, meetup);
        }

        return new MeetupRegistrationDTO(meetupsToRegistrations, registrationToMeetup);
    }
}