force-app/main/default/objects/Meetup__c/Meetup__c.object-meta.xml
<CustomObject>
    <label>Meetup</label>
    <nameField>
        <label>Meetup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meetup__c/fields/RegistrationCode__c.field-meta.xml
<CustomField>
    <fullName>RegistrationCode__c</fullName>
    <label>RegistrationCode</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MeetupTriggerHandler.cls
public with sharing class MeetupTriggerHandler extends TriggerHandler {
    private List<Meetup__c> triggerNew;

    public MeetupTriggerHandler() {
        this.triggerNew = (List<Meetup__c>) Trigger.new;
    }

    public override void beforeInsert() {
        for(Meetup__c meetup : this.triggerNew) {
            meetup.RegistrationCode__c = MeetupUtils.generateRegistrationCode();
        }
    }
}