force-app/main/default/objects/Meetup__c/Meetup__c.object-meta.xml
<CustomObject>
    <label>Meetup</label>
    <nameField>
        <label>Meetup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meetup__c/fields/RegistrationCount__c.field-meta.xml
<CustomField>
    <fullName>RegistrationCount__c</fullName>
    <label>RegistrationCount</label>
    <summaryForeignKey>MeetupRegistration__c.Meetup__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/MeetupRegistration__c/MeetupRegistration__c.object-meta.xml
<CustomObject>
    <label>MeetupRegistration</label>
    <nameField>
        <label>Registration Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MeetupRegistrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/MeetupRegistrationTriggerHandler.cls
public with sharing class MeetupRegistrationTriggerHandler extends TriggerHandler {
    List<MeetupRegistration__c> triggerNew;
    Map<Id, MeetupRegistration__c> triggerNewMap;
    MeetupRegistrationDTO dto;
    
    public MeetupRegistrationTriggerHandler() {
        this.triggerNew = (List<MeetupRegistration__c>) Trigger.new;
        this.dto = new MeetupRegistrationDAC(this.triggerNew).getDTO();
    }

    public override void beforeInsert(){
        for(MeetupRegistration__c registration : this.triggerNew) {
            Meetup__c meetup = this.dto.getMeetup(registration.Meetup__c);
            Integer regsSize = this.dto.getRegistrations(meetup.Id).size();
            if(meetup.RegistrationCount__c + regsSize > meetup.RegistrationLimit__c){
                registration.addError('You cannot exceed the meetup limit!');
            }
            
            registration.Name = String.valueOf(meetup.RegistrationCount__c + 1);
        }
    }
}