force-app/main/default/objects/Meetup__c/Meetup__c.object-meta.xml
<CustomObject>
    <label>Meetup</label>
    <nameField>
        <label>Meetup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meetup__c/fields/RegistrationCode__c.field-meta.xml
<CustomField>
    <fullName>RegistrationCode__c</fullName>
    <label>RegistrationCode</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestMeetupTriggerHandler.cls
@isTest(SeeAllData=false)
private class TestMeetupTriggerHandler {

    @isTest
    private static void testAutogenerateRegistrationCode() {
        List<Meetup__c> meetups = new List<Meetup__c>();
        
        for(Integer i = 0; i < 10; i++){
            meetups.add(new Meetup__c(
                Name = 'Meetup #' + i,
                RegistrationLimit__c = i,
                Status__c = 'Open'
            ));
        }

        insert meetups;


        for(Meetup__c meetup : [SELECT Id, RegistrationCode__c FROM Meetup__c]){
            System.assert(!String.isBlank(meetup.RegistrationCode__c), 'Registration Code should be auto generated for new records');
        }
    }
}